In [1]:
import pandas as pd
df = pd.read_csv("29Mai2023.csv")

In [2]:
df.drop('Instrument', axis=1, inplace=True)
df.drop('OpenInterest', axis=1, inplace=True)
df.drop('TradeTimestamp', axis=1, inplace=True)
df.drop('Timestamp', axis=1, inplace=True)

In [3]:
for i in range(50):
    #df[f'High{i+1}'] = df['High'].shift(i+1) - df['High']
    #df[f'Low{i+1}'] = df['Low'].shift(i+1) - df['Low']
    df[f'Actual{i+1}'] = df['Actual'].shift(i+1) -  df['Actual']
    df[f'Volume{i+1}'] = df['Volume'].shift(i+1) - df['Volume']
    #df[f'UsdVolume{i+1}'] = df['UsdVolume'].shift(i+1) - df['UsdVolume']
    df[f'Change{i+1}'] = df['Change'].shift(i+1) - df['Change']
    df[f'BestBid{i+1}'] = df['BestBid'].shift(i+1) - df['BestBid']
    df[f'BestBidSize{i+1}'] = df['BestBidSize'].shift(i+1) - df['BestBidSize']
    df[f'BestAsk{i+1}'] = df['BestAsk'].shift(i+1) - df['BestAsk']
    df[f'BestAskSize{i+1}'] = df['BestAskSize'].shift(i+1) - df['BestAskSize']
    

/tmp/ipykernel_19576/1766425678.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Volume{i+1}'] = df['Volume'].shift(i+1) - df['Volume']
/tmp/ipykernel_19576/1766425678.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Change{i+1}'] = df['Change'].shift(i+1) - df['Change']
/tmp/ipykernel_19576/1766425678.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) 

In [4]:
df[f'ActualF50'] = df['Actual'].shift(-50) -  df['Actual']
df['ActualF50'] = df['ActualF50'].apply(lambda x: 1 if x >= 1 else -1 if x <= -1 else 0)
df.drop('High', axis=1, inplace=True)
df.drop('Low', axis=1, inplace=True)
df.drop('Actual', axis=1, inplace=True)
df.drop('Volume', axis=1, inplace=True)
df.drop('UsdVolume', axis=1, inplace=True)
df.drop('Change', axis=1, inplace=True)
df.drop('BestBid', axis=1, inplace=True)
df.drop('BestBidSize', axis=1, inplace=True)
df.drop('BestAsk', axis=1, inplace=True)
df.drop('BestAskSize', axis=1, inplace=True)

/tmp/ipykernel_19576/3151075095.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'ActualF50'] = df['Actual'].shift(-50) -  df['Actual']


In [5]:
df = df[50:4879]
df = df.copy()

In [6]:
print(df)

      Actual1  Volume1  Change1  BestBid1  BestBidSize1  BestAsk1   
50       0.47  -1.0786   0.0003      0.22       -2.0701      0.04  \
51      -0.26  -0.0600  -0.0002      0.19        1.9000     -0.04   
52       0.05  -0.0600   0.0000     -0.01        0.1998      0.39   
53       0.23  -0.0100   0.0002      0.11       -0.1997      0.00   
54      -0.14  -0.0155  -0.0001      0.03        0.0000      0.00   
...       ...      ...      ...       ...           ...       ...   
4874     0.24  -0.0400   0.0001      0.26       -7.4921      0.28   
4875     0.30  -0.3600   0.0002      0.22        7.3410      0.09   
4876    -0.01   0.0710   0.0002      0.00        0.0000      0.17   
4877     0.22  -0.0167   0.0001      0.00        0.0067      0.10   
4878     0.70  -2.8265   0.0004      0.62       -4.3477      0.64   

      BestAskSize1  Actual2  Volume2  Change2  ...  BestAsk49  BestAskSize49   
50          0.0000     0.48  -1.1386   0.0003  ...      -0.04         0.0000  \
51         

In [7]:
for i in range(50):
    print(df[f'Volume{i+1}'].unique())

[-1.0786 -0.06   -0.06   ... -0.1603  0.071  -2.8265]
[-1.1386 -1.1386 -0.12   ... -0.289   0.0543 -2.8432]
[-1.1986 -0.13   -0.0855 ... -0.329  -0.3057 -2.7722]
[-1.2248 -1.2586 -1.2586 ... -0.3382 -0.3457 -3.1322]
[-1.2348 -1.2848 -1.3186 ... -0.4985 -0.3549 -3.1722]
[-1.2548 -1.2948 -1.3448 ... -0.5618 -0.5152 -3.1814]
[-1.2702 -1.3148 -1.3548 ... -0.6729 -0.5785 -3.3417]
[-1.4282 -1.3302 -1.3748 ... -0.6882 -0.6896 -3.405 ]
[-1.4455 -1.4882 -1.3902 ... -1.3404 -0.7049 -3.5161]
[ -1.7055  -1.5055  -1.5482 ... -28.7414  -1.3571  -3.5314]
[ -2.6733  -1.7655  -1.5655 ... -28.7605 -28.7581  -4.1836]
[ -1.7907  -2.7333  -1.8255 ... -28.7968 -28.7772 -31.5846]
[ -1.803   -1.8507  -2.7933 ... -28.8175 -28.8135 -31.6037]
[ -1.8166  -1.863   -1.9107 ... -28.8374 -28.8342 -31.64  ]
[ -4.4542  -1.8766  -1.923  ... -28.8568 -28.8541 -31.6607]
[ -4.4642  -4.5142  -1.9366 ... -28.8978 -28.8735 -31.6806]
[ -5.0045  -4.5242  -4.5742 ... -28.9369 -28.9145 -31.7   ]
[ -5.976   -5.0645  -4.5842 ... -2

In [8]:
zeros = df[df['ActualF50'] == 0]
ones  = df[df['ActualF50'] == 1]
negatives = df[df['ActualF50'] == -1]
print(zeros['ActualF50'])
print(ones['ActualF50'])
print(negatives['ActualF50'])

70      0
71      0
72      0
73      0
74      0
       ..
4874    0
4875    0
4876    0
4877    0
4878    0
Name: ActualF50, Length: 1939, dtype: int64
84      1
85      1
87      1
89      1
90      1
       ..
4830    1
4831    1
4834    1
4835    1
4836    1
Name: ActualF50, Length: 1379, dtype: int64
50     -1
51     -1
52     -1
53     -1
54     -1
       ..
4727   -1
4728   -1
4729   -1
4730   -1
4731   -1
Name: ActualF50, Length: 1511, dtype: int64


In [9]:
zeros = zeros.sample(frac=1).reset_index(drop=True)
zeros = zeros[:800]
df = pd.concat([zeros, ones, negatives])
df = df.sample(frac=1).reset_index(drop=True)
train_dataset = df.head(2000)
test_dataset = df.tail(df.shape[0] - 2000)

In [10]:
import os
import pandas as pd
from torch.utils.data import Dataset

class CustomPriceDataset(Dataset):
    def __init__(self, dataframe, labels, transform=None, target_transform=None):
        self.dataframe = dataframe
        self.labels = labels
        self.transform = transform
        self.target_transform = target_transform
        

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        data = list(self.dataframe.iloc[idx])
        label = self.labels.iloc[idx]
        if self.transform:
            data = self.transform(data)
        if self.target_transform:
            label = self.target_transform(label)
        return data, label

In [11]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision.transforms import ToTensor, Lambda

trnlbl = train_dataset['ActualF50'] + 1
trnset = train_dataset.drop('ActualF50', axis=1)
trainPrice = CustomPriceDataset(trnset, trnlbl, torch.FloatTensor, Lambda(lambda y: torch.zeros(3, dtype=torch.float).scatter_(0, torch.tensor(y), value=1)))
train_dataloader = DataLoader(trainPrice, batch_size=64)

tstlbl = test_dataset['ActualF50'] + 1
tstset = test_dataset.drop('ActualF50', axis=1)
testPrice = CustomPriceDataset(tstset, tstlbl, torch.FloatTensor)
test_dataloader = DataLoader(testPrice, batch_size=64)

In [12]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(350, 2048),
            nn.ReLU(),
            nn.Linear(2048, 1024),
            nn.ReLU(),
            nn.Linear(1024, 512),
            nn.ReLU(),
            nn.Linear(512, 128),
            nn.ReLU(),
            nn.Linear(128, 3),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork()

In [13]:
def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    for batch, (X, y) in enumerate(dataloader):
        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 20 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")


def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [14]:
learning_rate = 1e-2
passed = 0

In [15]:
epochs = 100
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=1e-2, dampening=1e-3)

In [16]:
print("Start")
for t in range(epochs):
    print(f"Epoch {t+1 + passed}\n-------------------------------")
    train_loop(train_dataloader, model, loss_fn, optimizer)
    test_loop(test_dataloader, model, loss_fn)
passed = passed + epochs
print("Done!")

Start
Epoch 1
-------------------------------
loss: 1.128855  [   64/ 2000]
loss: 1.070507  [ 1344/ 2000]
Test Error: 
 Accuracy: 50.3%, Avg loss: 1.044554 

Epoch 2
-------------------------------
loss: 1.027355  [   64/ 2000]
loss: 1.060597  [ 1344/ 2000]
Test Error: 
 Accuracy: 50.8%, Avg loss: 1.033070 

Epoch 3
-------------------------------
loss: 1.006080  [   64/ 2000]
loss: 1.050705  [ 1344/ 2000]
Test Error: 
 Accuracy: 49.7%, Avg loss: 1.025524 

Epoch 4
-------------------------------
loss: 0.988846  [   64/ 2000]
loss: 1.043953  [ 1344/ 2000]
Test Error: 
 Accuracy: 49.4%, Avg loss: 1.020293 

Epoch 5
-------------------------------
loss: 0.974786  [   64/ 2000]
loss: 1.036566  [ 1344/ 2000]
Test Error: 
 Accuracy: 49.9%, Avg loss: 1.015958 

Epoch 6
-------------------------------
loss: 0.963016  [   64/ 2000]
loss: 1.031253  [ 1344/ 2000]
Test Error: 
 Accuracy: 50.0%, Avg loss: 1.012457 

Epoch 7
-------------------------------
loss: 0.952138  [   64/ 2000]
loss: 1.0248

Test Error: 
 Accuracy: 50.0%, Avg loss: 1.071417 

Epoch 55
-------------------------------
loss: 0.624628  [   64/ 2000]
loss: 0.661609  [ 1344/ 2000]
Test Error: 
 Accuracy: 50.8%, Avg loss: 1.041389 

Epoch 56
-------------------------------
loss: 0.593108  [   64/ 2000]
loss: 0.697009  [ 1344/ 2000]
Test Error: 
 Accuracy: 48.9%, Avg loss: 1.100853 

Epoch 57
-------------------------------
loss: 0.631196  [   64/ 2000]
loss: 0.693706  [ 1344/ 2000]
Test Error: 
 Accuracy: 49.3%, Avg loss: 1.109333 

Epoch 58
-------------------------------
loss: 0.622581  [   64/ 2000]
loss: 0.624121  [ 1344/ 2000]
Test Error: 
 Accuracy: 50.1%, Avg loss: 1.079050 

Epoch 59
-------------------------------
loss: 0.581552  [   64/ 2000]
loss: 0.677989  [ 1344/ 2000]
Test Error: 
 Accuracy: 50.9%, Avg loss: 1.092566 

Epoch 60
-------------------------------
loss: 0.571594  [   64/ 2000]
loss: 0.727678  [ 1344/ 2000]
Test Error: 
 Accuracy: 50.4%, Avg loss: 1.107261 

Epoch 61
---------------------

In [17]:
for stuff in range(5):
    epochs = 20
    loss_fn = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=1e-2, dampening=1e-3)
    print("Start")
    for t in range(epochs):
        print(f"Epoch {t+1 + passed}\n-------------------------------")
        train_loop(train_dataloader, model, loss_fn, optimizer)
        test_loop(test_dataloader, model, loss_fn)
    passed = passed + epochs
    print("Done!")

Start
Epoch 101
-------------------------------
loss: 0.220762  [   64/ 2000]
loss: 0.125111  [ 1344/ 2000]
Test Error: 
 Accuracy: 53.1%, Avg loss: 1.397122 

Epoch 102
-------------------------------
loss: 0.306219  [   64/ 2000]
loss: 0.328828  [ 1344/ 2000]
Test Error: 
 Accuracy: 54.9%, Avg loss: 1.226441 

Epoch 103
-------------------------------
loss: 0.230715  [   64/ 2000]
loss: 0.158265  [ 1344/ 2000]
Test Error: 
 Accuracy: 54.1%, Avg loss: 1.300583 

Epoch 104
-------------------------------
loss: 0.224769  [   64/ 2000]
loss: 0.137153  [ 1344/ 2000]
Test Error: 
 Accuracy: 53.4%, Avg loss: 1.340072 

Epoch 105
-------------------------------
loss: 0.227912  [   64/ 2000]
loss: 0.107555  [ 1344/ 2000]
Test Error: 
 Accuracy: 51.7%, Avg loss: 1.718905 

Epoch 106
-------------------------------
loss: 0.384697  [   64/ 2000]
loss: 0.175838  [ 1344/ 2000]
Test Error: 
 Accuracy: 56.5%, Avg loss: 1.257272 

Epoch 107
-------------------------------
loss: 0.250371  [   64/ 2000

loss: 0.012900  [ 1344/ 2000]
Test Error: 
 Accuracy: 61.4%, Avg loss: 1.699887 

Epoch 155
-------------------------------
loss: 0.012329  [   64/ 2000]
loss: 0.011411  [ 1344/ 2000]
Test Error: 
 Accuracy: 61.1%, Avg loss: 1.720372 

Epoch 156
-------------------------------
loss: 0.011482  [   64/ 2000]
loss: 0.010717  [ 1344/ 2000]
Test Error: 
 Accuracy: 60.9%, Avg loss: 1.745284 

Epoch 157
-------------------------------
loss: 0.010612  [   64/ 2000]
loss: 0.010027  [ 1344/ 2000]
Test Error: 
 Accuracy: 61.1%, Avg loss: 1.774926 

Epoch 158
-------------------------------
loss: 0.009801  [   64/ 2000]
loss: 0.492412  [ 1344/ 2000]
Test Error: 
 Accuracy: 59.0%, Avg loss: 1.430533 

Epoch 159
-------------------------------
loss: 0.237911  [   64/ 2000]
loss: 0.064682  [ 1344/ 2000]
Test Error: 
 Accuracy: 57.8%, Avg loss: 1.516688 

Epoch 160
-------------------------------
loss: 0.072861  [   64/ 2000]
loss: 0.022256  [ 1344/ 2000]
Test Error: 
 Accuracy: 60.7%, Avg loss: 1.578